base:
  batch_size: 5192
  epochs: 20
  metrics:
    - AUC
    - GAUC
    - MRR
  optimizer: adam
  loss: binary_crossentropy
  learning_rate: 0.001
  gpu: 0
  patience: 2
  test_batch_size: 10240
  need_training: true

MostPopular:
  need_training: false


ContextRec:
  learning_rate: 0.1

DIN:
  batch_size: 512
  test_batch_size: 2048
  learning_rate: 0.00001

DIERM:
  learning_rate: 0.0001



