base:
  hidden_units:
    - 128
    - 128
  hidden_activations: ReLU

LR:
  model_id: LR

MostPopular:
  model_id: MostPopular

ContextRec:
  model_id: ContextRec

EventRec:
  model_id: EventRec

WideDeep:
  model_id: WideDeep

DeepFM:
  model_id: DeepFM

DIN:
  model_id: DIN
#  din_target_field:
#    - - event_id
#
#  din_sequence_field:
#    - - user_joined_events

DIERM:
  model_id: DIERM