base:
  hidden_units:
    - 128
    - 128
  hidden_activations: ReLU

LR:
  model_id: LR

MostPopular:
  model_id: MostPopular

ContextRec:
  model_id: ContextRec

EventRec:
  model_id: EventRec

WideDeep:
  model_id: WideDeep

DeepFM:
  model_id: DeepFM

DIN:
  model_id: DIN

DIERM:
  model_id: DIERM